### ISSUE TITLE
BUG: Target port not translated

### ISSUE THREAD

**Issue by lars18th** [alexte/sat-ip-proxy#13]
Hi @leecher1337 ,

When the listening RTSP port is different of the target RTSP port, then the translation requires to replace the port too. After this line:
https://github.com/alexte/sat-ip-proxy/blob/6d55aa2173c3adda229b84878adfb980786f3762/rtsp-proxy.c#L590
not only the server IP has to be changed, but also the port requires to be changed.

Please, can you fix it?
Thank you!

**Comment by leecher1337** [comment]
I think you are addressing the wrong person, I'm not the developer, you need to ask @alexte for it or fix it yourself, test it and add a pull request. I currently have no test setup for your issue, so I cannot help.

**Comment by lars18th** [comment]
> I think you are addressing the wrong person, I'm not the developer, you need to ask @alexte for it 

Sorry @leecher1337 , you're right!

Please @alexte , can you fix it?

**Comment by alexte** [comment]
Can you explain a configuration, which triggers this bug ?

I have to look into this a bit more.

**Comment by lars18th** [comment]
> Can you explain a configuration, which triggers this bug ?

Sure!

- If you execute the `rtsp-proxy` in a non-default port (!=554) _and_ the target SAT>IP uses the default port (554) then the translated request uses the _listening_ port instead of the _target_ port.
- Futhermore, if you execute the `rtsp-proxy` in the default port but the target SAT>IP uses an alternative RTSP port, then the translated request uses the default port instead of the real target port.
- And even, if you execute in the same machine a SAT>IP server in a non-default port and you run the `rtsp-proxy` in another non-default port, in this case the translated port is erroneous too, as they are different.

> I have to look into this a bit more.

It's quite simple: The _translated_ RTSP request requires a _translated_ **port**, and not only a translated address.

Regards.

**Comment by alexte** [comment]
Ah I see this happens because of the patch, to allow different ports on both ends. 

I remember not to translate the port number, because it was not needed with same port on both ends.

Haven't used this software for a while. It takes some time to get into it again.

**Comment by lars18th** [comment]
Hi @alexte ,

> Ah I see this happens because of the patch, to allow different ports on both ends.
> I remember not to translate the port number, because it was not needed with same port on both ends.

No really true! :wink: 
Previous to the patch the remote target port is every time 554, but the local can be any port. And in this case, the translation of the port is also incorrect. The difference now is that the cases can vary a bit more!

> Haven't used this software for a while. It takes some time to get into it again.

I understand it. However, I feel you can fix it without much effort.

Thank you for this small project. It's very useful! :+1:

**Comment by alexte** [comment]
The code before the patch used the same port on both ends, if I remember correctly.

I fixed it (probably) but don't know how to test it. 
All the servers and client I have use port 554 always.

**Comment by lars18th** [comment]
> I fixed it (probably) but don't know how to test it.
> All the servers and client I have use port 554 always.

Well done! It works! Thank you! :+1: 

In any case: two test it you can daisy-chain two instances:
`SAT>IP client ---> rtsp-proxy :554 ---> rtsp-proxy :20554 ---> SAT>IP SERVER :554`
In this case the second proxy will require to translate from 20554 to 554. And the first can connect to it as now it can change the target port. :wink:
