### ISSUE TITLE
Support for selectable UDP range (client-port)

### ISSUE THREAD

**Issue by lars18th** [alexte/sat-ip-proxy#8]
Hi,

When the rstp-client requests a SETUP command to the SAT>IP server, it uses the same port range as the client requests. This can create troubles:

1) If the same UDP port is in use in the machine where is running the proxy.

2) Or when the proxy is inside a NAT network.

So. I suggest to use a custom UDP port range in the proxy (independent to the ports used by the client), and make it selectable when starting the proxy (like "-r 51000-51100").

I hope you can implement it.

**Comment by alexte** [comment]
Thank you for your input. I will put it on the TODO list.

**Comment by lars18th** [comment]
Great! I hope you can implement it soon!

Thank you!

**Comment by lars18th** [comment]
Hi @alexte ,

Years after I implemented it. Please, merge it! #11 .

Regards.

**Comment by alexte** [comment]
What do you think ?

Does it work for you ?
